### ISSUE TITLE
Is there any docs available on Red5?

### ISSUE THREAD

**Issue by derwaldgeist** [Red5/red5-docs#2]
Hi guys,

I am very interested in this project, but completely lost, as I could not find any documentation on it. The homepage does only contain dummies, so is this documentation repository on GitHub.

I tried to install the Docker package, and it seems to be running, but I have absolutely no clue on where to get started. Live streaming is hot these days, so any OpenSource project in this field is great!

Cheers, Tom

**Comment by mondain** [comment]
There is a lot of documentation out there, but it may require a google search here and there. I suggest starting with the readme of the red5-server project and then progress onto the wiki pages.
